#!/bin/sh
IP=$1
NOTARY_URL=$5
PASSPHRASE='Harbor12345'

echo $IP

export DOCKER_CONTENT_TRUST=1
export DOCKER_CONTENT_TRUST_SERVER=$NOTARY_URL

export NOTARY_ROOT_PASSPHRASE=$PASSPHRASE
export NOTARY_TARGETS_PASSPHRASE=$PASSPHRASE
export NOTARY_SNAPSHOT_PASSPHRASE=$PASSPHRASE
export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE=$PASSPHRASE
export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$PASSPHRASE
export DOCKER_CONTENT_TRUST_OFFLINE_PASSPHRASE=$PASSPHRASE
export DOCKER_CONTENT_TRUST_TAGGING_PASSPHRASE=$PASSPHRASE

docker login -u admin -p Harbor12345 $IP
docker tag $3:$4 $IP/$2/$3:$4
docker push $IP/$2/$3:$4

